"""Smoke tests for ``src.models.precision_report`` (E3)."""

from __future__ import annotations

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

import pandas as pd

from src.models.precision_report import (
    collect_artefacts,
    per_year_set_validation,
    to_latex,
    to_markdown,
)


def test_per_year_returns_table_with_required_columns() -> None:
    df = per_year_set_validation()
    assert isinstance(df, pd.DataFrame)
    assert not df.empty
    for col in ("n_train", "n_test", "logloss", "auc", "brier", "acc"):
        assert col in df.columns
    # Temporada is the index (int).
    assert df.index.name == "temporada"
    assert all(isinstance(t, (int,)) for t in df.index)


def test_collect_artefacts_returns_known_keys() -> None:
    artefacts = collect_artefacts()
    assert "precision_improved" in artefacts
    assert "b4_blend" in artefacts
    assert "b5_churn" in artefacts
    # If precision_improved.json is present (it should be), the dict is non-empty.
    if artefacts["precision_improved"]:
        assert "match" in artefacts["precision_improved"]


def test_to_markdown_contains_sections() -> None:
    df = per_year_set_validation()
    md = to_markdown(df, collect_artefacts())
    for section in [
        "# Precision Report (E3)",
        "## Canonical Snapshot",
        "## Per-Year Set Validation",
        "## Existing JSON Artefacts",
    ]:
        assert section in md


def test_to_latex_returns_compilable_table() -> None:
    df = per_year_set_validation()
    tex = to_latex(df)
    assert tex.startswith("% Auto-generated by")
    assert r"\begin{tabular}{r r r r r r r}" in tex
    assert r"\end{tabular}" in tex
    # At least one data row per year (each row ends with ` \\`).
    assert tex.count(" \\\\") >= len(df)
